### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by TCWilliamson** [khoih-prog/AsyncUDP_Teensy41#1]
Hello!

Really great library you've put together,

Is there any chance you'd be willing to move to a more permissive license such as MIT?
GPLv3 is a nightmare if you want to consider using this library for anything remotely commercial. (or was that the intention?)

**Comment by khoih-prog** [comment]
I certainly prefer `MIT` licence, but this library is a port from [**ESPAsyncUDP** Library](https://github.com/me-no-dev/ESPAsyncUDP) and I didn't like to waste my time in legal research to know which one is correct to use, `MIT` or `GPLv3`.

Therefore I had to use the safer one, to avoid complaints, such as [**Clarification on the license?** #8](https://github.com/khoih-prog/AsyncHTTPRequest_Generic/issues/8)

If you can spend some time to research and be sure that `MIT` licence is OK, please inform me so that I can change to `MIT`

Anyway, this is not an issue of the library and my interest to spend time, I'm closing this now,  but still looking forward to receiving your information.

Regards,
